project:
  type: website

website:
  description: "Exploring lacrosse and other things of interest through an analytical lens with R."
  site-url: https://danalytics.blog 
  title: "danalytics"
  navbar:
    right:
      - text: About
        href: about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/dovertoo/danalytics
      - icon: twitter
        href: https://twitter.com/danovertoom
format:
  html:
    theme:
      dark: [pulse, theme-dark.scss]
      light: pulse
    css: styles.css
    respect-user-color-scheme: true
editor: visual

