project:
  type: website

website:
  description: "Exploring lacrosse and other things of interest through an analytical lens with R."
  site-url: https://danalytics.blog 
  title: "danalytics"
  navbar:
    right:
      - text: About
        href: about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/dovertoo/danalytics
      - icon: twitter
        href: https://twitter.com/danovertoom
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

